### ISSUE TITLE
clean up "skeleton"

### ISSUE THREAD

**Issue by flyingmachine** [braveclojure/open-source#3]
The "skeleton" namespaces are holdovers from my own little project skeleton that I copied. I think that "skeleton" is confusing; change to "open-source".

**Comment by looselytyped** [comment]
(Coming here from http://open-source.braveclojure.com/projects/open-source) 

Is this issue relevant anymore? Looking over the source I don't see any `skeleton` namespaces, however I do see https://github.com/braveclojure/open-source/commit/951c8ab756dbc26d73ce62e536b5867e315c1246 and https://github.com/braveclojure/open-source/commit/3b92410258651e56b5d68e70dfbd6ccb3674fc31 which seem to indicate this issue might be resolved.

**Comment by flyingmachine** [comment]
It's not, thanks!
